apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset 
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app:  my-app
    spec:
      containers:
        - image: sergnazarenko/devops
          name: nginx
          ports:
            - containerPort: 80